name: Upload Python Wheel to DBFS then run notebook using whl.

on:
  pull_request

env:
  DATABRICKS_HOST: https://e2-demo-tokyo.cloud.databricks.com/
  DATABRICKS_TOKEN: ${{ secrets.dbToken }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checks out the repo
        uses: actions/checkout@v2

      - name: Upload file
        uses: databricks/upload-dbfs-temp@v0
        id: upload_file
        with:
          local-path: test-harness/databricks_test_harness/run_tests.py
          dbfs-file-path:: 'dbfs:/tmp/jmaru/databricks-github-actions/'
          
      - name: Setup python
        uses: actions/setup-python@v2
        
      - name: Build wheel
        run:
          cd example |
          python setup.py bdist_wheel
          
      - name: Upload Wheel
        uses: databricks/upload-dbfs-temp@v0
        id: upload_wheel
        with:
          local-path: example/dist/databricks_tests_example-0.0.1-py3-none-any.whl
          dbfs-file-path:: 'dbfs:/tmp/jmaru/databricks-github-actions/'
